<?xml version="1.0"?>

<robot name="differential_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="wheel_diameter"  value="0.034"/>
  <xacro:property name="wheel_thickness" value="0.025"/>
  <xacro:property name="wheel_offset_z"  value="0.034"/>
  <xacro:property name="wheel_ori_x"     value="0.055"/>


  <xacro:property name="chassis_ori_z"  value="0.0605"/>
  <xacro:property name="chassis_size_x" value="0.175"/>
  <xacro:property name="chassis_size_y" value="0.11"/>
  <xacro:property name="chassis_size_z" value="0.027"/>

  <xacro:property name="laser_ori_x"  value="0.0275"/>

  <xacro:property name="imu_ori_x"  value="-0.095"/>

  <!-- Base link -->
  <link name="base_link"/>.

  <!-- Chassis -->
  <xacro:macro name="chassis">  
  <link name="chassis">
    <visual>
      <origin xyz="0 0 ${chassis_ori_z} " rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_size_x} ${chassis_size_y} ${chassis_size_z}"/>
      </geometry>
    </visual>
  </link>
  </xacro:macro>  
  <xacro:chassis/>

  <!-- Left Wheel -->
  <xacro:macro name="left_wheel">  
    <link name="left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_diameter}" length="${wheel_thickness}"/>
      </geometry>
    </visual>
    </link>
  </xacro:macro>  
  <xacro:left_wheel/>

  <!-- Right Wheel -->
  <xacro:macro name="right_wheel"> 
  <link name="right_wheel">
    <visual>
      <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_diameter}" length="${wheel_thickness}"/>
      </geometry>
    </visual>
  </link>
  </xacro:macro>  
  <xacro:right_wheel/>


  <!-- IMU -->
  <xacro:macro name="imu">
    <link name="imu">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.02 0.02 0.005"/>
        </geometry>
      </visual>
    </link>

  <joint name="imu_joint" type="fixed">
    <parent link="chassis"/>
    <child link="imu"/>
    <origin xyz="${imu_ori_x} -0.006 0.059" rpy="0 0 0"/>
  </joint>
  </xacro:macro>
  <xacro:imu/>


  <!-- LiDAR -->
  <xacro:macro name="laser">
    <link name="laser">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.035" length="0.04"/>
        </geometry>
      </visual>
    </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="chassis"/>
    <child link="laser"/>
    <origin xyz="${laser_ori_x} 0 ${chassis_size_z + chassis_ori_z}" rpy="0 0 0"/>
  </joint>
  </xacro:macro>
  <xacro:laser/>



  <!-- Joints -->
  <joint name="chassis_to_base" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
  </joint>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="chassis"/>
    <child link="left_wheel"/>
    <origin xyz="0.05 -0.0625 0.017" rpy="${-pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="chassis"/>
    <child link="right_wheel"/>
    <origin xyz="0.05 0.0625 0.017" rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

</robot>
